<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MT-PC" failures="0" tests="1" name="TestNG.Topic_08_TimeOut" time="1.020" errors="1" timestamp="2024-10-10T20:50:15 ICT" skipped="0">
  <testcase classname="TestNG.Topic_08_TimeOut" name="TC_01" time="1.020">
    <error message="Method TestNG.Topic_08_TimeOut.TC_01() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG.Topic_08_TimeOut.TC_01() didn't finish within the time-out 1000
at java.base@17.0.12/java.lang.Thread.sleep(Native Method)
at app//TestNG.Topic_08_TimeOut.TC_01(Topic_08_TimeOut.java:15)
at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.12/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.12/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.12/java.lang.Thread.run(Thread.java:842)
]]>
    </error>
  </testcase> <!-- TC_01 -->
</testsuite> <!-- TestNG.Topic_08_TimeOut -->
